### ISSUE TITLE
Growthmodels Package

### ISSUE THREAD

**Issue by JagdeeshK** [drodriguezperez/growthmodels#1]
I was using the gompertz model from the growthmodels package and have an issue.

Can someone confirm the equation used in the gompertz function? I used the example 
> growth <- gompertz(0:10, 10, 0.5, 0.3)
> print(growth) 
and got the result as:
 [1] 0.589298 0.844508 1.156148 1.520856 1.932103 2.381021 2.857364 3.350447 3.849939 4.346457
[11] 4.831945
Since Alphas is the upper asymptote, the max value should when t=10 should be near to 10. But the above value shows a max value of 4.83

But if we substitute Alpha, Beta and K as 10, 0.5 and 0.3 respectively to the gompertz growth model equation, y(t)=αexp(−βexp(−kt)),  we get a different value.
6.065306597
6.904518019
7.600235814
8.160457741
8.60194196
8.944331797
9.206738383
9.406085551
9.556543627
9.669555453
9.754137547

Am I doing something wrong here? Any help will be much appreciated.

Thanks,
Jagadeesh

**Comment by drodriguezperez** [comment]
I used the same code and get the rights results. Probably you have imported another package which overwrites the `gompertz` function. In this situations you can indicate the namespace of which the `gompertz` function is imported using:

> growthmodels::gompertz(0:10, 10, 0.5, 0.3)

**Comment by JagdeeshK** [comment]
Thank you for the quick response. Yes, it did work by using
growthmodels::gompertz()
