### ISSUE TITLE
Richards model 

### ISSUE THREAD

**Issue by DuyDN** [drodriguezperez/growthmodels#2]
Hi,
I am wondering what exactly the form the Richard model, there is several forms in the literature. Such as in the model fitting the weight (w) as function of week, I found three forms 
w = alpha/((1 + beta*exp(-k * week))^(1/m))
w = alpha*((1 + beta*exp(-k * week))^(1/m))
w = alpha*((1 + beta*exp(-k * week))^m
Do you have idea which is the correct one? 
Also, in the form of Richard model in the package, how can we drive the age at the inflection and the weight at the inflection?  I could not find the formula for this one but for other forms.
Thank you 
Duy

**Comment by drodriguezperez** [comment]
In growthmodels the Richads model is implemented as:

w = alpha / (1 + beta * exp(-k * t))^(1 / m)

but it is possible to see different implementations in different sources.
